server:
  port: 8020

spring:
  application:
    name: students-bff
  datasource:
    url: jdbc:h2:file:./data/studentsDB;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
